# Generated by Django 4.2.4 on 2023-12-14 03:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimpleThought",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("6c478fac-ecb4-4397-837a-f2fe33a755bc"), primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SimpleRelation",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("ca283611-ae98-4b44-8362-a46b15368f79"), primary_key=True, serialize=False
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="prototype.simplethought"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
