# Generated by Django 4.2.4 on 2023-12-14 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("prototype", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplerelation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8d10d39f-3674-4939-b005-c41e624f702e"), primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="simplethought",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("233596ea-4630-4987-ab3a-58e774fa6c04"), primary_key=True, serialize=False
            ),
        ),
    ]
