# Generated by Django 5.0.1 on 2024-02-21 02:51

import deep4.prototype.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="richtext",
            name="content",
            field=deep4.prototype.models.HtmlSanitizedTextField(default="<h1>new rich entry</h1>"),
        ),
    ]
