# Generated by Django 4.2.4 on 2023-12-14 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("prototype", "0002_alter_simplerelation_id_alter_simplethought_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplerelation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1e164ab1-b061-418f-8d73-ab26c5189d14"), primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="simplethought",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d2296f0d-f2ae-464f-8965-e37e83ddba0c"), primary_key=True, serialize=False
            ),
        ),
    ]
