# Generated by Django 5.0.1 on 2024-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0003_location_children_tag_location_node_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="children_tag",
            field=models.TextField(
                choices=[
                    ("ul", "list item"),
                    ("div class='row border'", "row"),
                    ("div class='col-sm border'", "column"),
                ],
                default="ul",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="node_tag",
            field=models.TextField(
                choices=[
                    ("li", "list item"),
                    ("div class='row border'", "row"),
                    ("div class='col-sm border'", "column"),
                    ("h1", "1 - heading"),
                    ("h3", "3 - heading"),
                    ("h5", "5 - heading"),
                ],
                default="li",
            ),
        ),
    ]
