# Generated by Django 5.0.1 on 2024-06-28 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0004_alter_location_children_tag_alter_location_node_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("short_description", models.TextField()),
                (
                    "child_group_tag",
                    models.TextField(
                        choices=[
                            ("ul", "list item"),
                            ("div class='row border'", "row"),
                            ("div class='col-sm border'", "column"),
                        ],
                        default="ul",
                    ),
                ),
                (
                    "child_element_tag",
                    models.TextField(
                        choices=[
                            ("li", "list item"),
                            ("div class='row border'", "row"),
                            ("div class='col-sm border'", "column"),
                            ("h1", "1 - heading"),
                            ("h3", "3 - heading"),
                            ("h5", "5 - heading"),
                        ],
                        default="li",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="location",
            name="children_tag",
        ),
        migrations.RemoveField(
            model_name="location",
            name="node_tag",
        ),
        migrations.AddField(
            model_name="location",
            name="frame",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="prototype.frame"
            ),
        ),
    ]
