# Generated by Django 5.0.1 on 2024-07-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0005_frame_remove_location_children_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="child_group_tag",
            field=models.TextField(
                choices=[("ul", "list"), ("div class='row border'", "row"), ("div class='col-sm border'", "column")],
                default="ul",
            ),
        ),
    ]
